### ISSUE TITLE
Different kinds of routes cause generation failure

### ISSUE THREAD

**Issue by bkimble** [rjurado01/rapidoc#5]
Given a route file like: 

```
Doc::Application.routes.draw do
  match 'dispatch', :to => 'mobile/dispatch#redirect', :constraints => { :id => /[A-Z]\d{5}/ }
  match 'dispatch', :to => 'dispatch#redirect'
  match "testing/foo.aspx", :to => "redirect#index"
  match '*path', :controller => 'redirect', :action => 'index'
end
```

Running rake rapidoc:generate  will result in:

```
  rake aborted!
  undefined method `split' for nil:NilClass

  rapidoc-0.0.5/lib/rapidoc/routes_doc.rb:72:in `add_resource_route'
  rapidoc-0.0.5/lib/rapidoc/routes_doc.rb:20:in `add_route'
  rapidoc-0.0.5/lib/rapidoc/resources_extractor.rb:23:in `block in get_routes_doc'
  rapidoc-0.0.5/lib/rapidoc/resources_extractor.rb:22:in `each'
```

As "controller_action" is nil when sent to add_resource_route.

As best as I can tell, it doesn't like routes with formats in the matcher (ie .aspx), it doesn't like duplicate  matching routes when one has a constraint the other doesn't, and it just doesn't like wildcard routes at all.

**Comment by rjurado01** [comment]
The problem is that when you execute 'rake rapidoc' it don't show any HTML methods for this routes.
I will try to fix it this weekend. 

Thanks for the warning.

**Comment by rjurado01** [comment]
Added support for more types of routes: https://github.com/drinor/rapidoc/commit/d8ce36bf48e7cbce33097a4a79e48f22da85b348

Upload to 0.0.6 version.
